<? 
//var get
$_SESSION["GLO_SeguridadIncludes"]= "";
$_SESSION['GLO_getid'] = "";
$_SESSION['GLO_getidp'] = "";
$_SESSION['GLO_getidf'] = "";
$_SESSION['GLO_msgE'] = "";
$_SESSION['GLO_msgC'] = "";
$_SESSION['GLO_msgI'] = "";
$_SESSION['GLO_msgE2'] = "";
$_SESSION['GLO_Focus'] = "";


//limpia las var de session generales a todos los sistemas
$_SESSION['TxtId'] ="";$_SESSION['TxtId2'] ="";
$_SESSION['TxtNumero']= "";
$_SESSION['TxtNroEntidad'] = "";
$_SESSION['TxtNroEntidad2'] = "";
$_SESSION['TxtQuery'] = "";
$_SESSION['campos'] ="";
$_SESSION["TxtIdManual"]="";
$_SESSION["TxtIdManualT"]="";
$_SESSION['TxtLocPage'] ="";//se usa x post, no como session

//Op
$_SESSION['OptCNC'] ="";
$_SESSION['OptTipo']="";
$_SESSION['OptTipoPR']="";
$_SESSION['OptTipoP'] = "";
$_SESSION['OptTipoG'] = "";$_SESSION['OptUniP']="";$_SESSION['OptUniT']="";
$_SESSION['OptTipoIVA'] ="";$_SESSION['OptTipoI'] ="";  
$_SESSION['Opt1'] ="";$_SESSION['Opt2'] ="";$_SESSION['Opt3'] ="";



//Ck
$_SESSION['ChkActivo']="";$_SESSION['ChkInactivo']= "";$_SESSION['ChkBaja']= ""; 
$_SESSION['ChkReq'] ="";$_SESSION['ChkVig']="";
$_SESSION['ChkSinVE']="";$_SESSION['ChkVtoCP']=""; 
$_SESSION['ChkPE']="";$_SESSION['ChkRE']="";$_SESSION['ChkPA']="";
$_SESSION['ChkEfe'] ="";$_SESSION['ChkChe'] ="";$_SESSION['ChkCC'] ="";
$_SESSION['ChkF1'] ="";$_SESSION['ChkF2'] ="";$_SESSION['ChkTipo'] ="";
$_SESSION['ChkRem'] ="";$_SESSION['ChkTran'] ="";$_SESSION['ChkTranD'] ="";
$_SESSION['ChkProp']="";$_SESSION['ChkAlq']="";$_SESSION['ChkLeas']="";$_SESSION['ChkAfe']="";
$_SESSION['CHkIA1']="";$_SESSION['CHkIA2']="";$_SESSION['CHkIA3']="";$_SESSION['TxtIA4']="";
$_SESSION['CHkIA5']="";$_SESSION['CHkIA6']="";$_SESSION['CHkIA7']="";$_SESSION['CHkIA8']="";
$_SESSION['ChkTeorico'] = "";
$_SESSION['ChkPractico'] = "";
$_SESSION['ChkEval'] = "";
$_SESSION['ChkEPP']="";
$_SESSION['ChkLibBomba']="";
$_SESSION['ChkAsistVap']="";
$_SESSION['ChkVE'] = "";
$_SESSION['ChkFirma'] ="";$_SESSION['ChkVer'] ="";
$_SESSION['ChkVtoE']="";
$_SESSION['ChkI1'] = "";$_SESSION['ChkI2'] = "";$_SESSION['ChkI3'] = "";$_SESSION['ChkI4'] = "";
$_SESSION['ChkI5'] = "";$_SESSION['ChkI6'] = "";$_SESSION['ChkI7'] = "";$_SESSION['ChkI8'] = "";
$_SESSION['ChkI9'] = "";$_SESSION['ChkI10'] = "";$_SESSION['ChkI11'] = "";$_SESSION['ChkI12'] = "";
$_SESSION['ChkPC']="";$_SESSION['ChkOC']="";
$_SESSION['ChkVtoCumpl']="";$_SESSION['ChkVtoCierre']="";
$_SESSION['ChkAceptada'] = "";
$_SESSION['ChkSA'] = "";$_SESSION['ChkD'] = "";
$_SESSION['ChkExtranjero'] = "";
$_SESSION['ChkC1'] = "";$_SESSION['ChkC2'] = "";$_SESSION['ChkC3'] = "";$_SESSION['ChkC4'] = "";$_SESSION['ChkC5'] = "";
$_SESSION['Chk1'] = "";$_SESSION['Chk2'] = "";$_SESSION['Chk3'] = "";
$_SESSION['ChkU1'] = "";$_SESSION['ChkU2'] = "";$_SESSION['ChkU3'] = "";
$_SESSION['ChkS1'] = "";$_SESSION['ChkS2'] = "";$_SESSION['ChkS3'] = "";

//CB
$_SESSION['CbAuto'] ="";$_SESSION['CbPAuto'] ="";$_SESSION['CbFabr']="";
$_SESSION['CbAseg']= "";$_SESSION['CbProducto']= "";
$_SESSION['CbTurno'] = "";$_SESSION['CbAgenda'] = "";$_SESSION['CbTipoContrato']= "";
$_SESSION['CbActividad'] = "";$_SESSION['CbAct'] ="";
$_SESSION['CbCliente'] ="";$_SESSION['CbCliente2'] ="";
$_SESSION['CbPersonal'] ="";$_SESSION['CbPersonal1'] ="";$_SESSION['CbPersonal2'] ="";
$_SESSION['CbUnidad'] ="";$_SESSION['CbUnidad2']="";
$_SESSION['CbMetodo'] ="";$_SESSION['CbMedio'] ="";
$_SESSION['CbProveedor'] ="";$_SESSION['CbProv']="";
$_SESSION['CbPropietarioEC']="";$_SESSION['CbPropietarioEF']="";$_SESSION['CbPropietarioIF']="";
$_SESSION['CbIVA']="";$_SESSION['CbIva'] ="";
$_SESSION['CbLocalidad'] ="";$_SESSION['CbLocalidadL'] ="";
$_SESSION['CbOrden']="";
$_SESSION['CbPago'] ="";
$_SESSION['CbTipo']="";$_SESSION['CbTipo2']="";
$_SESSION['CbTipoCong']="";$_SESSION['CbTipoV']="";$_SESSION['CbTipoH'] = "";$_SESSION['CbTipoS'] = "";
$_SESSION['CbServicio']="";
$_SESSION['CbCentro']="";$_SESSION['CbBECtro']="";
$_SESSION['CbSit']="";$_SESSION['CbSitR']="";
$_SESSION['CbSituacionP']="";$_SESSION['CbOS']="";
$_SESSION['CbSituacionR']="";$_SESSION['CbServicioGrabado']="";$_SESSION['CbOSGrabado']="";$_SESSION['CbSituacionRGrab']="";
$_SESSION['CbYacimiento']="";$_SESSION['CbYac']="";$_SESSION['CbOp']="";$_SESSION['CbOp2']="";
$_SESSION['CbOrigen'] ="";$_SESSION['TxtOrigen'] ="";
$_SESSION['CbEstado'] ="";$_SESSION['CbEstadoP'] ="";
$_SESSION['CbEtapa'] ="";
$_SESSION['CbCausa'] ="";
$_SESSION['CbItem'] ="";$_SESSION['CbItem1']="";$_SESSION['CbItem2']="";
$_SESSION['CbFuncion']="";$_SESSION['CbEnv']="";
$_SESSION['CbTipoEst']="";$_SESSION['CbVacio']="";
$_SESSION['CbPerfil'] = "";
$_SESSION['CbAnio']="";$_SESSION['CbCurso']="";
$_SESSION['CbSectorCU']="";
$_SESSION['CbTema']="";$_SESSION['CbEstadoCP']="";$_SESSION['CbCursoCP']="";$_SESSION['CbPersonalCP']="";
$_SESSION['CbFormador'] ="";
$_SESSION['CbVto']=""; 
$_SESSION['CbRes'] ="";
$_SESSION['CbPrio'] = "";
$_SESSION['CbRubro']="";
$_SESSION['CbMoneda'] ="";
$_SESSION['CbPC']="";
$_SESSION['CbInstrumento']="";
$_SESSION['CbMarca']="";$_SESSION['CbMarca2']="";
$_SESSION['CbBECtro']="";$_SESSION['CbTH'] = "";$_SESSION['CbRS']="";$_SESSION['CbPersAf']="";
$_SESSION['CbPartCausa1'] = "";$_SESSION['CbPartCausa2'] = "";$_SESSION['CbPartCausa3'] = "";
$_SESSION['CbPartCausa4'] = "";$_SESSION['CbPartCausa5'] = "";$_SESSION['CbPartCausa6'] = "";
$_SESSION['CbRespAccion1CO'] = "";$_SESSION['CbRespAccion2CO'] = "";$_SESSION['CbRespAccion3CO'] = "";
$_SESSION['CbRespAccion4CO'] = "";$_SESSION['CbRespAccion5CO'] = "";$_SESSION['CbRespAccion6CO'] = "";
$_SESSION['CbRespAccion1'] = "";$_SESSION['CbRespAccion2'] = "";$_SESSION['CbRespAccion3'] = "";
$_SESSION['CbRespAccion4'] = "";$_SESSION['CbRespAccion5'] = "";$_SESSION['CbRespAccion6'] = "";
$_SESSION['CbVerif'] = "";$_SESSION['CbNuevaNC'] = "";
$_SESSION['CbServ']="";$_SESSION['CbCateg']="";$_SESSION['CbCateg2']="";
$_SESSION['CbNroInterno']="";
$_SESSION['CbCond']="";$_SESSION['CbEje'] ="";
$_SESSION['CbDesvio'] ="";
$_SESSION['CbEC'] ="";$_SESSION['CbDocumento'] = "";
$_SESSION['CbCUIT'] ="";$_SESSION['CbART'] ="";
$_SESSION['CbEstudios'] ="";
$_SESSION['CbNorma'] = "";
$_SESSION['CbNorma1'] = "";
$_SESSION['CbNorma2'] = "";
$_SESSION['CbNorma3'] = "";
$_SESSION['CbReq1'] = "";
$_SESSION['CbReq2'] = "";
$_SESSION['CbReq3'] = "";
$_SESSION['CbReq4'] = "";
$_SESSION['CbReq5'] = "";
$_SESSION['CbReq6'] = "";
$_SESSION['CbSector'] = "";$_SESSION['CbSector2'] = "";$_SESSION['CbSector3'] = "";$_SESSION['CbSector4'] = "";
$_SESSION['CbRespDet'] = "";
$_SESSION['CbPartAI'] = "";
$_SESSION['CbUnM'] = "";$_SESSION['CbTipoC'] ="";$_SESSION['CbTipoCertif'] =  "";
$_SESSION['CbTInstrumento']="";$_SESSION['CbCertif']="";
$_SESSION['CbTipoMS']="";$_SESSION['CbDeposito']="";$_SESSION['CbOS']="";
$_SESSION['CbInst']="";
$_SESSION['CbFl'] ="";
$_SESSION['CbConf'] ="";
$_SESSION['CbCantP']="";$_SESSION['CbTipoP']="";$_SESSION['CbTipoQ']="";
$_SESSION['CbMani'] ="";$_SESSION['CbManiI'] ="";
$_SESSION['CbTema'] = "";$_SESSION['CbContrato'] ="";$_SESSION['CbCC'] ="";
$_SESSION['CbTipoE']="";
$_SESSION['CbP1'] = "";
$_SESSION['CbP2'] = "";
$_SESSION['CbP3'] = "";
$_SESSION['CbU1'] = "";
$_SESSION['CbU2'] = "";
$_SESSION['CbU3'] = "";
$_SESSION['CbU4'] = "";
$_SESSION['CbU5'] = "";
$_SESSION['CbU6'] = "";
$_SESSION['CbU7'] = "";
$_SESSION['CbU8'] = "";
$_SESSION['CbEU1'] = "";
$_SESSION['CbEU2'] = "";
$_SESSION['CbEU3'] = "";
$_SESSION['CbEU4'] = "";
$_SESSION['CbEU5'] = "";
$_SESSION['CbEU6'] = "";
$_SESSION['CbEU7'] = "";
$_SESSION['CbEU8'] = "";
$_SESSION['CbDesvioT'] ="";	
$_SESSION['CbProceso'] ="";
$_SESSION['CbEstadoNC']="";$_SESSION['CbEstadoPC']="";$_SESSION['CbEstadoOC']="";
$_SESSION['CbPPED']="";$_SESSION['CbPrio']="";
$_SESSION['CbTServ'] ="";
$_SESSION['CbProfesional']="";$_SESSION['CbNC'] = "";
$_SESSION['CbFrec']= "";
$_SESSION['CbResp'] =  "";$_SESSION['CbOlf'] =  "";

//querys q deben limpiarse
$_SESSION['TxtIdPadre'] = "";$_SESSION['TxtIdPE1IT'] = "";$_SESSION['TxtIdPE2IT'] = "";
$_SESSION['TxtRespDet'] = "";
$_SESSION['TxtQREPORDT']= "";$_SESSION['TxtQREPORDTA']= "";
$_SESSION['TxtQCONCERITEMS']= "";
$_SESSION['TxtQCOITEMS']= "";
$_SESSION['TxtQCOPCIT']="";
$_SESSION['TxtQCOOCITV']="";
$_SESSION['TxtQSTREIT']= "";
$_SESSION['TxtQSTRIIT']= "";
$_SESSION["TxtQNOTAPDET"]="";
$_SESSION['TxtQuery74']="";
$_SESSION['TxtQPREPU1']="";
$_SESSION['TxtQPREPU2']="";
$_SESSION['TxtConsultaHCCaso']=""; 
$_SESSION['TxtConsultaHCCert']="";
$_SESSION['TxtConsultaHCPeso']="";
$_SESSION['TxtConsultaHCVac']="";
$_SESSION['TxtConsultaHCAlcohol']="";
$_SESSION['TxtConsultaHCRep']="";
$_SESSION['TxtQVISITT']= "";
$_SESSION['TxtQHCDrogas']="";
$_SESSION['TxtQISOPLAT']= "";
$_SESSION['TxtQVISITT']= "";
$_SESSION['TxtQHCI7']="";
$_SESSION['TxtQHCI8']="";$_SESSION['TxtQSTOCKDEPPLR'] = "";
$_SESSION['TxtQArtBI'] = "";


//Txt
$_SESSION['TxtTemp'] = "";$_SESSION['TxtIdCAM'] = "";$_SESSION['TxtCliente'] = "";
$_SESSION['TxtIdRto'] = "";$_SESSION['TxtIdRtoE'] = "";$_SESSION['TxtIdRtoI'] = "";
$_SESSION['TxtDNITramite'] = "";$_SESSION['TxtFactor']="";
$_SESSION['TxtNumeroI'] ="";$_SESSION['TxtBultos'] ="";
$_SESSION['TxtNumeroC']="";
$_SESSION['TxtIdCaso']="";
$_SESSION['TxtNroPI']="";
$_SESSION['TxtEfe'] ="";
$_SESSION['TxtChe'] ="";
$_SESSION['TxtF1'] ="";
$_SESSION['TxtF2'] ="";
$_SESSION['TxtRem'] ="";
$_SESSION['TxtCantidadA'] ="";
$_SESSION["TxtNroContrato"]="";
$_SESSION['TxtDesc'] ="";
$_SESSION['TxtAnio'] = "";
$_SESSION['TxtNumero1']= "";
$_SESSION['TxtIdEstado'] = "";
$_SESSION['TxtIdCumpl'] = "";
$_SESSION['TxtEstado'] = "";$_SESSION['TxtEstado2'] = "";
$_SESSION['TxtCumpl'] = "";
$_SESSION['TxtDescripcion'] = "";
$_SESSION['TxtDesAI'] = "";
$_SESSION['TxtFechaAI'] = "";
$_SESSION['TxtCausa'] = "";
$_SESSION['TxtAccionCO'] = "";
$_SESSION['TxtOtrosRCO'] = "";
$_SESSION['TxtOtrosRMCO'] = "";
$_SESSION['TxtFPlazoCO'] = "";
$_SESSION['TxtFCumplCO'] = "";
$_SESSION['TxtAccion'] = "";
$_SESSION['TxtFPlazo'] = "";
$_SESSION['TxtFCumpl'] = "";
$_SESSION['TxtFPrevista'] = "";
$_SESSION['TxtFCierre'] = "";
$_SESSION['TxtObsVerif'] = "";
$_SESSION['TxtObsNP'] = "";
$_SESSION['TxtOtrosP'] = "";
$_SESSION['TxtOtrosPM'] = "";
$_SESSION['TxtOtrosR'] = "";
$_SESSION['TxtOtrosRM'] = "";
$_SESSION['TxtNroOrden'] ="";
$_SESSION['TxtNroCP'] ="";
$_SESSION['TxtNroDT'] ="";
$_SESSION['TxtCentro'] ="";
$_SESSION['TxtIdPC'] ="";
$_SESSION['TxtTipoSer']= "";
$_SESSION['TxtFlag2']="";
$_SESSION['TxtRazon'] ="";
$_SESSION['TxtReq'] = "";
$_SESSION['TxtExCriterio'] ="";$_SESSION['TxtExCriterio2'] ="";
$_SESSION['TxtNroOC']="";$_SESSION['TxtNroOC2']="";$_SESSION['TxtRto']="";$_SESSION['TxtLote']="";
$_SESSION['TxtNroPedido']="";
$_SESSION['TxtIdContrato'] ="";$_SESSION['TxtIdCot'] ="";
$_SESSION['TxtConsulta']="";
$_SESSION['TxtApellido'] = "";
$_SESSION['TxtBusqueda']="";
$_SESSION['TxtBusquedaCUIT']="";
$_SESSION['TxtCheque'] ="";
$_SESSION['TxtClaveActual'] = "";
$_SESSION['TxtClave'] = "";
$_SESSION['TxtConfirmar'] = "";
$_SESSION['TxtCP'] = "";
$_SESSION['TxtCUIT'] ="";
$_SESSION['TxtDireccion'] = "";
$_SESSION['TxtDomi'] ="";
$_SESSION['TxtEMail'] = "";
$_SESSION['TxtFactura'] ="";
$_SESSION['TxtFechaA'] ="";$_SESSION['TxtFecha']="";$_SESSION['TxtFechaB'] = "";
$_SESSION['TxtFechaD']="";$_SESSION['TxtFechaH']="";$_SESSION['TxtFechaP'] ="";$_SESSION['TxtFechaV'] ="";
 $_SESSION['TxtFechaE'] = "";$_SESSION['TxtFechaI']="";$_SESSION['TxtFechaF']="";$_SESSION['TxtFechaG']="";
$_SESSION['TxtFecha1'] ="";$_SESSION['TxtFecha2'] ="";$_SESSION['TxtFecha3'] ="";$_SESSION['TxtFecha4'] ="";
$_SESSION['TxtFechaVE'] = "";$_SESSION['TxtFechaR'] = "";$_SESSION['TxtFechaDCP'] ="";$_SESSION['TxtFechaHCP'] ="";
$_SESSION['TxtFechaFH']="";
$_SESSION['TxtFechaDHid']="";$_SESSION['TxtFechaHHid']="";$_SESSION['TxtFechaDEPPRec']="";$_SESSION['TxtFechaHEPPRec']="";
$_SESSION['TxtFechaU1'] ="";$_SESSION['TxtFechaU2'] ="";$_SESSION['TxtFechaU3'] ="";
$_SESSION['TxtFechaS1'] ="";$_SESSION['TxtFechaS2'] ="";$_SESSION['TxtFechaS3'] ="";
$_SESSION['TxtFechaC'] ="";$_SESSION['TxtFechaC1'] ="";$_SESSION['TxtFechaC2'] ="";



$_SESSION['TxtLoc'] ="";
$_SESSION['TxtLogo'] = "";
$_SESSION['TxtMailF'] = "";
$_SESSION['TxtMailT'] = "";
$_SESSION['TxtNombre'] ="";$_SESSION['TxtStock'] = "";
$_SESSION['TxtNombreF'] = "";
$_SESSION['TxtNro']="";
$_SESSION['TxtPagina'] ="";
$_SESSION['TxtPass'] = "";
$_SESSION['TxtPOP'] = "";
$_SESSION['TxtProvincia'] = "";
$_SESSION['TxtSMTP'] = "";
$_SESSION['TxtSTitulo'] ="";
$_SESSION['TxtTelefono'] = "";$_SESSION['TxtTel'] = "";
$_SESSION['TxtTexto'] ="";
$_SESSION['TxtTitulo'] = "";
$_SESSION['TxtTotal'] ="";
$_SESSION['TxtUrgente']=""; 
$_SESSION['TxtUsuario'] = "";
$_SESSION['TxtPath']="";
$_SESSION['TxtObs'] ="";$_SESSION['TxtObs1'] ="";$_SESSION['TxtObs2'] ="";$_SESSION['TxtObs3'] ="";$_SESSION['TxtObs4'] ="";$_SESSION['TxtObs5'] ="";
$_SESSION['TxtNroInterno']="";
$_SESSION['TxtPesAf']="";
$_SESSION['TxtHoraI']="";$_SESSION['TxtHoraS']="";$_SESSION['TxtHoraT']="";$_SESSION['TxtIdCtro']="";$_SESSION['TxtIdServicio']="";
$_SESSION['TxtPersonal']='';
$_SESSION['TxtObsAct']="";$_SESSION['TxtTieneItems']="";$_SESSION['TxtTieneDT']="";
$_SESSION['TxtFReal']="";$_SESSION['TxtFObj']="";$_SESSION['TxtFCumpl']="";$_SESSION['TxtFCumpl2']="";
$_SESSION['TxtHReal']="";$_SESSION['TxtHObj']="";$_SESSION['TxtHCumpl']="";$_SESSION['TxtHCumpl2']="";
$_SESSION['TxtIdTipoS']="";$_SESSION['TxtCantServ']="";
$_SESSION['TxtIdCtro'] ="";$_SESSION['TxtIdCentro'] ="";
$_SESSION['TxtFechaProg']="";
$_SESSION['TxtNroOrden'] ="";
$_SESSION['TxtNroCP'] ="";
$_SESSION['TxtNroDT'] ="";
$_SESSION['TxtInst'] ="";
$_SESSION['TxtCantidad'] ="";
$_SESSION['TxtIdCliente']="";
$_SESSION['TxtIdContrato']="";
$_SESSION['TxtCant']="";$_SESSION['TxtCant1']="";$_SESSION['TxtCant2']="";$_SESSION['TxtCant3']="";
$_SESSION['TxtCantP']="";$_SESSION['TxtCantU']="";
$_SESSION['TxtBusquedaI']="";
$_SESSION['TxtIdCliOri'] = "";
$_SESSION['TxtModelo'] = "";$_SESSION['TxtModelo2'] = "";
$_SESSION['TxtSerie'] = "";
$_SESSION['TxtFrec'] = "";$_SESSION['TxtFrec1'] = "";$_SESSION['TxtFrec2'] = "";
$_SESSION['TxtSuc']="";$_SESSION['TxtNro']="";
$_SESSION['TxtCantidadInicial'] ="";
$_SESSION['TxtCantidadP'] ="";
$_SESSION['TxtArticulo'] ="";
$_SESSION['TxtIdArticulo'] ="";
$_SESSION['TxtNroNP'] ="";
$_SESSION['TxtObsAct']="";
$_SESSION['TxtHV']="";$_SESSION['TxtH50']="";$_SESSION['TxtH100']="";$_SESSION['TxtVi']="";$_SESSION['TxtViDes']="";
$_SESSION['TxtDN']="";$_SESSION['TxtDA']="";$_SESSION['TxtDFRT']="";$_SESSION['TxtDF']="";
$_SESSION['TxtDE']="";$_SESSION['TxtDT']="";$_SESSION['TxtDV']="";$_SESSION['TxtDL']="";$_SESSION['TxtDS']="";$_SESSION['TxtDAcc']="";$_SESSION['TxtDFC']="";
$_SESSION['TxtNSE'] =  "";
$_SESSION['TxtFoto'] =  "";
$_SESSION['TxtRango1'] = "";
$_SESSION['TxtRango2'] = "";
$_SESSION['TxtObsBaja'] = "";
$_SESSION['TxtTAG'] = "";
$_SESSION['TxtCertif'] =  "";
$_SESSION['TxtArchivo']=  "";
$_SESSION['TxtIdCentroProg']="";
$_SESSION['TxtNroProgCtro']="";
$_SESSION['TxtIdContrato']="";
$_SESSION['TxtInst'] ="";
$_SESSION['TxtM3I'] ="";
$_SESSION['TxtMotConf']="";
$_SESSION['TxtPresionI']="";
$_SESSION['TxtPresionM']="";
$_SESSION['TxtPresionF']="";
$_SESSION['TxtTempB']="";
$_SESSION['TxtLitrosQ']="";
$_SESSION['TxtLugarI']="";
$_SESSION['TxtLugarR']="";
$_SESSION['TxtIdInst']="";$_SESSION['TxtIdItem']="";$_SESSION['TxtItem']="";
$_SESSION['TxtInst'] ="";
$_SESSION['TxtProfBomba']="";
$_SESSION['TxtCCParaf']="";
$_SESSION['TxtProfCarre']="";
$_SESSION['TxtLibTension']="";
$_SESSION['TxtTipoSisa']="";
$_SESSION['TxtHsVapor']="";
$_SESSION['TxtIdInst']="";
$_SESSION['TxtOp1']="";
$_SESSION['TxtOp2']="";
$_SESSION['TxtCodigo'] = "";
$_SESSION['TxtCodigo1'] = "";
$_SESSION['TxtTitulo'] = "";
$_SESSION['TxtTemario'] = "";
$_SESSION['TxtDuracion'] = "";
$_SESSION['TxtCosto'] = "";
$_SESSION['TxtEval'] = "";
$_SESSION['TxtObsVE'] = "";
$_SESSION['TxtCumpl'] ="";
$_SESSION['TxtNroFact'] ="";
$_SESSION['TxtNroImpreso'] ="";
$_SESSION['TxtFechaDUEPP']="";$_SESSION['TxtFechaHUEPP']="";
$_SESSION['TxtIdPers'] = "";
$_SESSION['TxtTalle'] = "";
$_SESSION['TxtTalle1'] = "";
$_SESSION['TxtTalle2'] = "";
$_SESSION['TxtTalle3'] = "";
$_SESSION['TxtTalle4'] = "";
$_SESSION['TxtLegajo'] = "";
$_SESSION['TxtDoc'] = "";$_SESSION['TxtDoc2'] = "";
$_SESSION['TxtCUIT'] = "";
$_SESSION['TxtFoto'] = "";
$_SESSION['TxtEdad'] = "";
$_SESSION['TxtLN'] = "";
$_SESSION['TxtNacionalidad'] = "";
$_SESSION['TxtCarga'] = "";
$_SESSION['TxtOSocial'] = "";
$_SESSION['TxtCatOS'] = "";
$_SESSION['TxtConv'] = "";
$_SESSION['TxtCP'] = "";
$_SESSION['TxtDireccionL'] = "";
$_SESSION['TxtProvinciaL'] = "";
$_SESSION['TxtCPL'] = "";
$_SESSION['TxtEMail'] = "";
$_SESSION['TxtTurno'] = "";
$_SESSION['TxtFuncion'] = "";
$_SESSION['TxtVtoLN'] = "";
$_SESSION['TxtVtoEP'] = "";
$_SESSION['TxtVtoLNP'] = "";
$_SESSION['TxtVtoPas'] = "";
$_SESSION['TxtVtoCarnet'] = "";
$_SESSION['TxtVtoCMD'] = "";
$_SESSION['TxtOrg'] ="";
$_SESSION['TxtBusquedaU']="";
$_SESSION['TxtBusquedaN']="";
$_SESSION['TxtHora'] ="";$_SESSION['TxtHoraD'] ="";
$_SESSION['TxtDir'] ="";$_SESSION['TxtDir2'] ="";
$_SESSION['TxtObj'] ="";$_SESSION['TxtMeta'] ="";
$_SESSION['TxtAlc'] ="";
$_SESSION['TxtOP'] ="";
$_SESSION['TxtAP'] ="";
$_SESSION['TxtNC'] ="";
$_SESSION['TxtTipo']="";$_SESSION['TxtSuc']="";$_SESSION['TxtNro']="";
$_SESSION['TxtST'] ="";
$_SESSION['TxtIVA'] ="";
$_SESSION['TxtOI'] ="";
$_SESSION['TxtTO'] ="";
$_SESSION['TxtCUIT'] = "";
$_SESSION['TxtCP'] = "";
$_SESSION['TxtEMail'] = "";
$_SESSION['TxtDiv'] ="";
$_SESSION['TxtNroI'] ="";
$_SESSION['TxtMet'] ="";
$_SESSION['TxtRes'] ="";
$_SESSION['TxtCri'] ="";
$_SESSION['TxtLogoAdd'] ="";
$_SESSION['TxtDesA'] ="";
$_SESSION['TxtTipoEntidad'] ="";
$_SESSION['TxtCod'] ="";
$_SESSION['TxtInterno'] ="";
$_SESSION['TxtCumplCon'] ="";
$_SESSION['TxtIdNC']= "";
$_SESSION['TxtImporte'] ="";
$_SESSION['TxtH'] = "";
$_SESSION['TxtOp'] = "";
$_SESSION['TxtMin'] ="";
$_SESSION['TxtMax'] ="";

$_SESSION['TxtContacto'] ="";
$_SESSION['TxtLugar'] ="";$_SESSION['TxtLugar1'] ="";$_SESSION['TxtLugar2'] ="";
$_SESSION['TxtNroCli'] ="";$_SESSION['TxtVal'] ="";
$_SESSION['TxtRef'] ="";
$_SESSION['TxtTitulo'] = "";
$_SESSION['TxtSTitulo'] ="";
$_SESSION['TxtTexto'] ="";
$_SESSION['TxtUrgente']=""; 
$_SESSION['TxtNumeroP']=""; 
$_SESSION['TxtPaciente']=""; 
$_SESSION['TxtNumeroA']=""; 
$_SESSION['TxtART']=""; 
$_SESSION['TxtDNI']=""; 
$_SESSION['TxtPuesto']=""; 
$_SESSION['TxtSexo']=""; 
$_SESSION['TxtDC1'] = "";
$_SESSION['TxtDC2'] = "";
$_SESSION['TxtDC3'] = "";
$_SESSION['TxtDC4'] = "";
$_SESSION['TxtDC5'] = "";
$_SESSION['TxtDC6'] = "";
$_SESSION['TxtDC7'] = "";
$_SESSION['TxtDC8'] = "";
$_SESSION['TxtDC9'] = "";
$_SESSION['TxtDC10'] = "";
$_SESSION['TxtDP1'] = "";
$_SESSION['TxtDP2'] = "";
$_SESSION['TxtDP3'] = "";
$_SESSION['TxtDP4'] = "";
$_SESSION['TxtDP5'] = "";
$_SESSION['TxtDP6'] = "";
$_SESSION['TxtDP7'] = "";
$_SESSION['TxtDiag']="";
$_SESSION['TxtRec']="";
$_SESSION['TxtProfesional']="";
$_SESSION['TxtMotivo']="";
$_SESSION['TxtNumeroI']="";
$_SESSION['TxtDirigido']="";
$_SESSION['TxtCargo']="";
$_SESSION['TxtEmpresa']="";
$_SESSION['TxtInforme']="";
$_SESSION['TxtIdCaso']="";
$_SESSION['TxtFVolverI']="";
$_SESSION['TxtQ1']="";$_SESSION['TxtQ2']="";$_SESSION['TxtQ3']="";$_SESSION['TxtQ5']="";$_SESSION['TxtQ6']="";
$_SESSION['TxtCod']= ""; 
$_SESSION['TxtVs']= ""; 
$_SESSION['CbPers1']= ""; 
$_SESSION['CbProv1']= ""; 
$_SESSION['TxtIdPers2']= ""; 
$_SESSION['TxtIdPers3']= ""; 
$_SESSION['TxtCod']= ""; 
$_SESSION['TxtVs']= ""; 
$_SESSION['TxtPers1']= ""; 
$_SESSION['TxtProv1']= ""; 
$_SESSION['TxtPers2']= ""; 
$_SESSION['TxtPers3']= ""; 
$_SESSION['TxtCom1']= ""; $_SESSION['TxtCom2']= ""; $_SESSION['TxtCom3']= ""; 
$_SESSION['TxtFO']= ""; 
$_SESSION['TxtFR']= ""; 
$_SESSION['TxtFVS']= ""; 
$_SESSION['TxtId']= "";
$_SESSION['TxtIdPers2']= ""; 
$_SESSION['TxtIdPers3']= ""; 
$_SESSION['TxtIdEstado']= "";
$_SESSION['CbPer'] ="";
$_SESSION['TxtIdent'] ="";
$_SESSION['TxtResp']= "";
$_SESSION['TxtVerif'] ="";
$_SESSION['TxtLic']=""; $_SESSION['TxtLic2']=""; $_SESSION['TxtVto']=""; $_SESSION['TxtVto2']=""; $_SESSION['TxtCat']=""; $_SESSION['TxtCat2']="";$_SESSION['TxtNombre2']="";$_SESSION['TxtAseg']="";$_SESSION['TxtPat']="";$_SESSION['TxtPol']="";
$_SESSION['TxtC']= "";$_SESSION['TxtS']= "";$_SESSION['TxtP']= "";$_SESSION['TxtC2']= "";$_SESSION['TxtS2']= "";$_SESSION['TxtP2']= "";
$_SESSION['TxtDerrame'] ="";$_SESSION['TxtSup'] ="";
$_SESSION['TxtTercero'] ="";$_SESSION['TxtPorc'] ="";
$_SESSION['TxtLocalidad2'] ="";$_SESSION['TxtProvincia2'] ="";$_SESSION['TxtCP2'] ="";
$_SESSION['TxtSector'] ="";$_SESSION['TxtEquipo'] ="";$_SESSION['TxtTpoE'] ="";$_SESSION['TxtTpoP'] ="";
$_SESSION['TxtHs'] ="";$_SESSION['TxtDias'] ="";
$_SESSION['TxtTN1'] ="";$_SESSION['TxtTE1'] ="";$_SESSION['TxtTC1'] ="";$_SESSION['TxtTT1'] ="";
$_SESSION['TxtTN2'] ="";$_SESSION['TxtTE2'] ="";$_SESSION['TxtTC2'] ="";$_SESSION['TxtTT2'] ="";
$_SESSION['TxtTN3'] ="";$_SESSION['TxtTE3'] ="";$_SESSION['TxtTC3'] ="";$_SESSION['TxtTT3'] ="";
$_SESSION['TxtTN4'] ="";$_SESSION['TxtTE4'] ="";$_SESSION['TxtTC4'] ="";$_SESSION['TxtTT4'] ="";
$_SESSION['TxtAlergia'] = "";
$_SESSION['TxtGrupoS'] = "";
$_SESSION['CbDiag']="";
$_SESSION['TxtMed']="";
$_SESSION['TxtMat']="";
$_SESSION['TxtPeso']="";
$_SESSION['TxtPMax']="";
$_SESSION['TxtPMin']="";
$_SESSION['CbVac']="";
$_SESSION['TxtDolar']="";
$_SESSION['TxtUbic'] = "";
$_SESSION['CbProd'] = "";
$_SESSION['TxtCap'] = "";
$_SESSION['OptA1'] = "";
$_SESSION['OptA2'] = "";
$_SESSION['OptA3'] = "";
$_SESSION['OptA4'] = "";
$_SESSION['OptA5'] = "";
$_SESSION['TxtUserA']= ""; 
$_SESSION['TxtDominio']= ""; $_SESSION['TxtDominio2']= ""; 
$_SESSION['TxtSedronar']="";$_SESSION['TxtIdOp'] = "";

//reparaciones
$_SESSION['TxtNroPR']="";$_SESSION['TxtNroOR']="";$_SESSION['ChkSOrden']="";$_SESSION['ChkSSoli']="";$_SESSION['CbEstadoS']="";
$_SESSION['TxtQueryRepReq']="";$_SESSION['TxtQueryRepIns']="";$_SESSION['TxtQueryRepReqSoli']="";$_SESSION['TxtQueryRepTar']="";
$_SESSION['TxtTieneReq']= ""; $_SESSION['TxtIdUnidad'] = "";$_SESSION['TxtServ'] = "";$_SESSION['TxtEstadoS'] = "";
$_SESSION['TxtIdEstadoS'] = "";$_SESSION['TxtIdOrden'] = "";$_SESSION['CbUrg'] ="";$_SESSION['TxtIdAccCumpl'] = "";
$_SESSION['TxtEstadoO'] = "";$_SESSION['TxtIdEstadoO'] = "";$_SESSION['TxtSoliS'] = "";$_SESSION['TxtTipoS'] = "";
$_SESSION['CbSoli'] = "";$_SESSION['CbSoli1'] = "";$_SESSION['TxtFechaS'] = "";$_SESSION['TxtFechaSI'] = "";$_SESSION['TxtIdSoli'] = "";
$_SESSION['TxtObsPL']= "";$_SESSION['CbPersonalPL']= "";$_SESSION['ChkListoPL']= "";$_SESSION['CbClase'] ="";
$_SESSION['TxtFecha6'] =  "";$_SESSION['TxtKm'] =  "";$_SESSION['TxtKm2'] =  "";$_SESSION['ChkPdte']= "";
$_SESSION['TxtPRUnidad'] ="";$_SESSION['TxtPRIdUnidad'] ="";$_SESSION['TxtPRServ'] ="";$_SESSION['TxtPRFechaI'] ="";
$_SESSION['TxtPRKm'] ="";$_SESSION['TxtPRHs'] ="";$_SESSION['TxtEstadoA'] ="";$_SESSION['TxtIdEstadoA'] ="";
$_SESSION['TxtHora1'] ="";$_SESSION['TxtHora2'] ="";$_SESSION['ChkISE'] ="";
$_SESSION['TxtPSI'] ="";$_SESSION['TxtMIM'] ="";$_SESSION['TxtFechaM'] ="";


//procesos
$_SESSION['TxtNumero1']="";$_SESSION['TxtNumero2']="";$_SESSION['TxtNumero3']="";$_SESSION['TxtNumero4']="";$_SESSION['TxtNumero5']="";
$_SESSION['TxtNumero6']="";$_SESSION['TxtNumero7']="";$_SESSION['TxtNumero8']="";$_SESSION['TxtNumero9']="";$_SESSION['TxtNumero10']="";
$_SESSION['TxtNumero11']="";
$_SESSION['CbEstado2']="";$_SESSION['CbEstado6']="";
$_SESSION['CbPersonal1']="";$_SESSION['CbPersonal10']="";$_SESSION['CbPersonal11']="";
$_SESSION['CbUnidad1']="";$_SESSION['CbUnidad10']="";$_SESSION['CbUnidad11']="";
$_SESSION['CbDep']="";$_SESSION['CbDep2']="";$_SESSION['CbDep3']="";$_SESSION['CbDep5']="";$_SESSION['CbDep7']="";
$_SESSION['TxtE1']="";$_SESSION['TxtE2']="";$_SESSION['TxtE3']="";$_SESSION['TxtE4']="";$_SESSION['TxtE5']="";$_SESSION['TxtE6']="";
$_SESSION['TxtE7']="";$_SESSION['TxtE8']="";$_SESSION['TxtE9']="";$_SESSION['TxtE10']="";$_SESSION['TxtE11']="";

$_SESSION['TxtChofer']="";
?>