<? if ($_SESSION["IdPerfilUser"]!=1 and $_SESSION["IdPerfilUser"]!=2 and $_SESSION["IdPerfilUser"]!=3 and $_SESSION["IdPerfilUser"]!=9 and $_SESSION["IdPerfilUser"]!=14 ){ header("Location:".$_SESSION["NivelArbol"]."Inicio.php");}

GLO_tituloypath(0,720,'../ExtintoresSMA.php','EXTINTORES','linksalir'); 
?>


<table width="720" border="0"  cellspacing="0" class="Tabla" >
<tr><td width="100" height="3"  ></td> <td width="100"></td> <td width="20"></td><td width="160"></td><td width="100" height="3"  ></td> <td width="50"></td><td width="50"></td><td width="50"></td><td width="90"></td> </tr>
<tr><td height="18"  align="right"  >N&uacute;mero:</td><td  valign="top" colspan="3">&nbsp;<input  name="TxtNro" type="text"  class="TextBox" tabindex="1"  align="right"   value="<? echo $_SESSION['TxtNro'];?>" onChange="this.value=validarEntero(this.value);" style="text-align:right;width:60px"><label class="MuestraError"> * </label></td><td height="18"  align="right"  >Chapa:</td><td style="color:#4CAF50; font-weight:bold">&nbsp;<input name="OptA1"   type="radio"  class="radiob"  value="B"<? if ($_SESSION['OptA1'] =='B') echo 'checked'; ?> >B</td><td style="color:#cc0099; font-weight:bold">&nbsp;<input name="OptA1"  type="radio"  class="radiob"  value="R"<? if ($_SESSION['OptA1'] =='R') echo 'checked'; ?> >R</td><td style=" color:#CC0000;font-weight:bold;"><input name="OptA1"  type="radio"  class="radiob"  value="M"<? if ($_SESSION['OptA1'] =='M') echo 'checked'; ?> >M</td><td></td></tr>
<tr><td height="18"  align="right"  >Unidad:</td><td  valign="top" colspan="3">&nbsp;<select name="CbUnidad" tabindex="1"  style="width:150px" class="campos" id="CbUnidad" ><option value=""></option> <? GLO_ComboActivoUni("unidades","CbUnidad","Dominio","","",$conn); ?> </select><label class="MuestraError"> * </label></td><td height="18"  align="right"  >Manguera:</td><td style="color:#4CAF50; font-weight:bold">&nbsp;<input name="OptA2"  type="radio"  class="radiob"  value="B"<? if ($_SESSION['OptA2'] =='B') echo 'checked'; ?> >B</td><td style="color:#cc0099; font-weight:bold">&nbsp;<input name="OptA2"  type="radio"  class="radiob"  value="R"<? if ($_SESSION['OptA2'] =='R') echo 'checked'; ?> >R</td><td style=" color:#CC0000;font-weight:bold;"><input name="OptA2"  type="radio"  class="radiob"  value="M"<? if ($_SESSION['OptA2'] =='M') echo 'checked'; ?> >M</td><td></td></tr>
<tr><td height="18"  align="right"  >Ubicaci&oacute;n:</td><td  valign="top" colspan="3">&nbsp;<select name="TxtUbic" tabindex="1"  style="width:150px" class="campos" id="TxtUbic" ><option value=""></option> <? ComboTablaRFX("extintoresubi","TxtUbic","Nombre","","",$conn); ?> </select></td><td height="18"  align="right"  >Collar&iacute;n:</td><td style="color:#4CAF50; font-weight:bold">&nbsp;<input name="OptA3"  type="radio"  class="radiob"  value="B"<? if ($_SESSION['OptA3'] =='B') echo 'checked'; ?> >B</td><td style="color:#cc0099; font-weight:bold">&nbsp;<input name="OptA3"  type="radio"  class="radiob"  value="R"<? if ($_SESSION['OptA3'] =='R') echo 'checked'; ?> >R</td><td style=" color:#CC0000;font-weight:bold;"><input name="OptA3"  type="radio"  class="radiob"  value="M"<? if ($_SESSION['OptA3'] =='M') echo 'checked'; ?> >M</td><td></td></tr>
<tr><td height="18"  align="right"  >Producto:</td><td  valign="top" colspan="3">&nbsp;<select name="CbProd" tabindex="1"  style="width:150px" class="campos" id="CbProd" ><option value=""></option> <? ComboTablaRFX("extintoresprod","CbProd","Nombre","","",$conn); ?> </select></td><td height="18"  align="right"  >Precinto:</td><td style="color:#4CAF50; font-weight:bold">&nbsp;<input name="OptA4"  type="radio"  class="radiob"  value="B"<? if ($_SESSION['OptA4'] =='B') echo 'checked'; ?> >B</td><td style="color:#cc0099; font-weight:bold">&nbsp;<input name="OptA4"  type="radio"  class="radiob"  value="R"<? if ($_SESSION['OptA4'] =='R') echo 'checked'; ?> >R</td><td style=" color:#CC0000;font-weight:bold;"><input name="OptA4"  type="radio"  class="radiob"  value="M"<? if ($_SESSION['OptA4'] =='M') echo 'checked'; ?> >M</td><td></td></tr>
<tr><td height="18"  align="right"  >Capacidad:</td><td  valign="top" colspan="3">&nbsp;<input name="TxtCap"  type="text"  class="TextBox"  style="text-align:right;width:50px" maxlength="7" tabindex="1" value="<? echo $_SESSION['TxtCap']; ?>" onChange="this.value=validarNumero(this.value);"></td><td height="18"  align="right"  >Exterior:</td><td style="color:#4CAF50; font-weight:bold">&nbsp;<input name="OptA5"  type="radio"  class="radiob"  value="B"<? if ($_SESSION['OptA5'] =='B') echo 'checked'; ?> >B</td><td style="color:#cc0099; font-weight:bold">&nbsp;<input name="OptA5"  type="radio"  class="radiob"  value="R"<? if ($_SESSION['OptA5'] =='R') echo 'checked'; ?> >R</td><td style=" color:#CC0000;font-weight:bold;"><input name="OptA5"  type="radio"  class="radiob"  value="M"<? if ($_SESSION['OptA5'] =='M') echo 'checked'; ?> >M</td><td></td></tr>
</table>

<table width="720" border="0"  cellspacing="0" class="Tabla TMT" >
<tr><td width="100" height="3"  ></td> <td width="100"></td> <td width="20"></td><td width="160"></td><td width="100" height="3"  ></td> <td width="50"></td><td width="50"></td><td width="50"></td><td width="90"></td> </tr>
<tr><td height="18"  align="right"  >Fecha Vto:</td><td  valign="top">&nbsp;<? GLO_calendario("TxtFechaA","../Codigo/","actual",1) ?></td><td height="18" ><label class="MuestraError"> * </label></td><td  valign="top" >VtoPH:&nbsp;<? GLO_calendario("TxtFechaB","../Codigo/","actual",1) ?></td><td  align="right"  >Baja:</td><td  valign="top" colspan="4"><input name="ChkBaja"  type="checkbox"  value="1" <? if ($_SESSION['ChkBaja'] =='1') echo 'checked'; ?>></td></tr>
</table>

<? 
GLO_obsform(720,100,'Estado','TxtObs',2,0);
GLO_Hidden('TxtNumero',0);GLO_Hidden('TxtId',0);
GLO_botonesform("720",0,2); 
GLO_mensajeerror();
?>